config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'user/nodes'
  resources :nodes
  get '/get_node_payout_data' => 'nodes#payout_data'

  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/donations', to: 'home#donations'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/node.rb
class Node < ApplicationRecord

  enum status: [:waiting, :connected]


  after_create :set_status_waiting


  require 'iota'

  validates_length_of :name, :minimum => 2, :maximum => 100
  validates_presence_of :url
  validate :valid_iota_address

  belongs_to :user

  def validate! _key

    require 'digest'
    require 'json'

    public_id = Digest::SHA2.hexdigest _key

    uri = URI('https://nutzdoch.einfachiota.de/nodes/' + URI::encode(name))
    response = Net::HTTP.get(uri) # => String
    data = JSON.parse(response)
    if public_id.starts_with? data["key"]
      self.connected!
      return true
    else
      errors.add(:key, :blank, message: "wrong key detected!")
      return false
    end

  end

  private

  def set_status_waiting
    self.waiting!
  end


  def valid_iota_address
    if self.donation_address
      utils = IOTA::Utils::InputValidator.new
      errors.add(:donation_address, "Not a valid iota address.") unless utils.isAddress(self.donation_address)
    end
  end



end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
    @register_new_node = params[:register_new_node] || "true"
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    if params[:node][:key]

      respond_to do |format|
        unless @node.validate! params[:node][:key]
          format.html { render :show }
          format.json { render json: @node.errors, status: :unprocessable_entity }
        end
      end
    end
    ## prüfe ob node key in den params ist und validate it!

    @node.user = current_user
    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update

    if params[:commit] == "Add key"

      respond_to do |format|
        if @node.validate! params[:node][:key]
          format.html { redirect_to @node, notice: 'Node was successfully updated.' }
          format.json { render :show, status: :ok, location: @node }
        else
          format.html { render :show }
          format.json { render json: @node.errors, status: :unprocessable_entity }
        end
      end
      # validate key
    else

      respond_to do |format|
        if @node.update(node_params)
          format.html { redirect_to @node, notice: 'Node was successfully updated.' }
          format.json { render :show, status: :ok, location: @node }
        else
          format.html { render :edit }
          format.json { render json: @node.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def payout_data
    nodes = Node.where(status: :connected)
    uri = URI(Rails.configuration.distribution_service_url)
    response =  Net::HTTP.get(uri)# => String
    data = JSON.parse(response)

    pp "nodes.count"
    pp nodes.count
    pp "data.count"
    pp data.count
    @payout_data = []

    data.each do |entry|
      pp "entry.name"
      pp entry["name"]
      node = nodes.find_by_name(entry["name"])
      if node
        pp "found!"
        payout_object = {
          name: node.name,
          address: node.donation_address,
          points: entry["points"],
          share: entry["share"]
        }
        @payout_data.push(payout_object)
      end
    end
    @payout_data
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def node_params
      params.require(:node).permit(:url, :name, :pow, :key, :donation_address)
    end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_with(model: node, local: true) do |form| %>
  <% if node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :url, "Add your node address:" %>
    <%= form.text_field :url, class: 'form-control', placeholder: 'https://node.einfachiota.de' %>
  </div>

  <div class="form-group">
    <%= form.label :name, "Add your favourite node name:" %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'einfachIOTA Node' %>
  </div>

  <div class="field form-group">
   <div class="checkbox-inline">
     Select the checkbox if Proof of Work is activated on your node.<br>
     <%= form.check_box :pow %>
     <%= form.label :pow, "PoW" %>
   </div>
 </div>

  <div class="form-group">
    <%= form.label :donation_address, "Your donation address:" %>
    <%= form.text_field :donation_address, class: 'form-control', placeholder: 'ABCDEF9..' %>
  </div>

  <% if new_node == "false" %>
  <div class="form-group">
    <%= form.label :key, "Your pool key:" %>
    <%= form.text_field :key, class: 'form-control', placeholder: 'ABCDEF9..', required: true %>
  </div>

  <% end %>

  <div class="form-group">
    <% if node.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', node, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if node.persisted? %>
      <%= link_to "Cancel", node, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", nodes_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/nodes/edit.html.erb
<h1>Edit Node</h1>

<%= render 'form', node: @node %>

app/views/nodes/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Nodes</h1>
    <p>This a list of nodes, which are registred on the Pool Manager and participate on the donation distribution. It's possible to join the piri pool without be registrated in the pool manager. These nodes will not be part of the donation disitrbution.</p>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_node_path, class: 'btn btn-primary' do %>
    Add New Node
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>

        <th>Name</th>
        <th>Status</th>

      </tr>
    </thead>

    <tbody>
      <% @nodes.each do |node| %>
        <%= content_tag :tr, id: dom_id(node), class: dom_class(node) do %>

            <td><%= link_to node.name, node %></td>
            <td><%= node.status %></td>


        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/nodes/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-md">


        <% if @register_new_node == "false" %>
        <h1>Connect a node</h1>
          <div class="alert alert-warning" role="alert">
            You can connect your node, which is currently in the pool. Just use the same name and url like in the pool registration!
          </div>
        <% else %>
        <h1>Register a new node</h1>
          Add a new node to the pool! Just add the correct node address and use a cool name!
        <% end %>
        <hr>


        <%= render 'form', node: @node, new_node: @register_new_node %>

        <% if @register_new_node == "true" %>
          <p>Your node is already registered in the node pool? <%= link_to "Click here", new_node_url(register_new_node: false) %></p>
        <% else %>
          <p>Your node is not registred the node pool right now? <%= link_to "Click here", new_node_url(register_new_node: true) %> to register a new one!</p>
        <% end %>

    </div>
  </div>
</div>

app/views/nodes/show.html.erb
<div class="page-header">
  <%= link_to nodes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    All Nodes
  <% end %>
  <%= link_to edit_node_path(@node), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <hr>
  <h5>Your Node:</h5>
  <h1><%= @node.name %></h1>
</div>
<h2>Node Information</h2>
<dl class="dl-horizontal">
  <dt>Url:</dt>
  <dd><%= @node.url %></dd>

  <dt>Pow:</dt>
  <dd><%= @node.pow %></dd>

</dl>

<% if @node.connected? %>
  <p>Node connected to piri pool</p>
<% else %>
<h2>Connect your node</h2>
<p>Copy this curl command and <strong> execute this on your server!</strong> Copy the returned key and insert it in the field below!</p>
<p></p>

<div class="alert alert-info" role="alert">
  curl -X POST "https://nutzdoch.einfachiota.de/nodes" -H  "accept: */*" -H  "Content-Type: application/json" -d "{  \"name\": \"<%= @node.name %>\",  \"url\": \"<%= @node.url %>\",  \"pow\": <%= @node.pow   %>}"
</div>

<%= form_with(model: @node, local: true) do |form| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :key %>
    <%= form.text_field :key, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit "Add key", class: 'btn btn-primary' %>
  </div>
<% end %>


<% end %>